import { builtinModules } from 'node:module'
import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'
import tseslint from 'typescript-eslint'

// Boundary rules, see docs/decisions/0005-linting-and-boundaries.md.
const tokensCoreForbidden = [
  'react',
  'react-dom',
  'express',
  // Bare Node built-ins ('fs', 'path', ...) as well as the 'node:' forms.
  ...builtinModules,
]

const apiDbMessage =
  'Only apps/api/src/db and apps/api/src/repositories may import the Prisma client, its adapter or pg: go through a repository (ADR 0012).'
const apiDbPaths = ['@prisma/client', '@prisma/adapter-pg', 'pg'].map(
  (name) => ({ name, message: apiDbMessage }),
)
const apiDbPattern = {
  group: ['@prisma/*', '**/generated/prisma', '**/generated/prisma/*'],
  message: apiDbMessage,
}
const apiIssueScopePattern = {
  group: ['**/tenancy/scope'],
  importNames: ['issueTenantScope'],
  message:
    'issueTenantScope is the only way to make a TenantScope and is reserved for the auth middleware (apps/api/src/auth). Tests may use it.',
}

export default defineConfig([
  globalIgnores([
    '**/dist/**',
    '**/coverage/**',
    '**/node_modules/**',
    '**/storybook-static/**',
    // Generated by `prisma generate` (not committed).
    'apps/api/src/generated/**',
    '**/playwright-report/**',
    '**/test-results/**',
  ]),

  js.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Browser code: the Theme Editor and the component library.
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    extends: [
      reactHooks.configs.flat.recommended,
      jsxA11y.flatConfigs.recommended,
    ],
    languageOptions: { globals: globals.browser },
  },

  // Node code: the API, scripts and tool configs.
  {
    files: [
      'apps/api/**',
      'scripts/**',
      'packages/*/scripts/**',
      'eslint.config.mjs',
      '**/*.config.ts',
    ],
    languageOptions: { globals: globals.node },
  },

  // Playwright specs run in Node (page.evaluate callbacks still use DOM types).
  {
    files: ['packages/ui/e2e/**/*.ts'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },

  // Boundary 1: packages/ui source must not import tokens-core. Build scripts
  // outside src/ may (ADR 0001/0002: build-time generation of the default theme).
  {
    files: ['packages/ui/src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@dts/tokens-core',
              message:
                'packages/ui/src must not import @dts/tokens-core: components only read CSS custom properties. Build scripts outside src/ may.',
            },
          ],
          patterns: [
            {
              group: ['@dts/tokens-core/*'],
              message:
                'packages/ui/src must not import @dts/tokens-core: components only read CSS custom properties. Build scripts outside src/ may.',
            },
          ],
        },
      ],
    },
  },

  // Boundary 2: tokens-core source is pure logic (no React, Express or Node).
  // Tests and config files are exempt.
  {
    files: ['packages/tokens-core/src/**/*.ts'],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: tokensCoreForbidden.map((name) => ({
            name,
            message:
              'packages/tokens-core/src must stay pure: no react, react-dom, express or Node built-ins.',
          })),
          patterns: [
            {
              group: ['node:*', 'react/*', 'react-dom/*', 'express/*'],
              message:
                'packages/tokens-core/src must stay pure: no react, react-dom, express or Node built-ins.',
            },
          ],
        },
      ],
    },
  },

  // Boundary 3 (ADR 0012): apps/api. Only src/db/** and src/repositories/** may
  // import the Prisma client, its adapter or `pg`, so every query goes through a
  // repository that takes a TenantScope. Tests, scripts and seed files live
  // outside src/ and are not restricted. And `issueTenantScope` (the only way to
  // make a TenantScope) may only be imported by the auth middleware (src/auth/**).
  {
    files: ['apps/api/src/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { paths: apiDbPaths, patterns: [apiDbPattern, apiIssueScopePattern] },
      ],
    },
  },
  {
    files: ['apps/api/src/db/**/*.ts', 'apps/api/src/repositories/**/*.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [apiIssueScopePattern] }],
    },
  },
  {
    files: ['apps/api/src/auth/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        { paths: apiDbPaths, patterns: [apiDbPattern] },
      ],
    },
  },
])
